Struct test
kuzaleks/collab pull request #8
Opened 2016-08-22 14:12 UTC by lirik30

2016-08-22 19:49 UTC, kuzaleks commented on test_struct/src/test_str.h
> +      TSM_ASSERT_EQUALS("The general case hasn't passed the test!", is_equal_files("start_general_case.bin", "ready_general_case.bin"), true);
Для начала, давайте договоримся придерживаться стандарта, согласна которому длинна строки не должна превышать 74 символа.

2016-08-22 19:49 UTC, kuzaleks commented on test_struct/src/test_str.h
> +    bool is_equal_files(const char* name_of_start_file, const char* name_of_ready_file)
Данный метод явно просится стать private.

2016-08-22 19:51 UTC, kuzaleks commented on test_struct/src/test_str.h
> +    bool is_equal_files(const char* name_of_start_file, const char* name_of_ready_file)
Давайте будем последовательно использовать стил camelCase для имен переменных и методов.

2016-08-22 19:52 UTC, kuzaleks commented on test_struct/str.cpp
> +Student Input()
Почему имя функции с большой буквы?

2016-08-23 07:28 UTC, lirik30 commented on test_struct/src/test_str.h
> +      TSM_ASSERT_EQUALS("The general case hasn't passed the test!", is_equal_files("start_general_case.bin", "ready_general_case.bin"), true);
Исправил всё, но оказалось, что если поменять длину строки, то появляется ошибка "Segmentation fault (core dumped)". Если ставить 97 и выше, всё нормально.

2016-08-28 15:25 UTC, kuzaleks commented on test_struct/src/test_str.h
> +      TSM_ASSERT_EQUALS("The general case hasn't passed the test!", is_equal_files("start_general_case.bin", "ready_general_case.bin"), true);
@lirik30 , гляньте ссылку: http://www.cplusplus.com/forum/beginner/38985/

2016-08-28 17:09 UTC, lirik30 commented on test_struct/src/test_str.h
> +      TSM_ASSERT_EQUALS("The general case hasn't passed the test!", is_equal_files("start_general_case.bin", "ready_general_case.bin"), true);
Дело в том, что эталонные файлы были записаны с учётом того, что размер строки name был равен 100 байт, а когда я изменял её длину на другое число, появлялась выше упомянутая ошибка. Вся соль в том, что даже если поставить длину строки как нужно, создать новые файлы, то тест всё равно может провалиться только потому, что у студента размер строки был 30, а у нас, например, те же 74. Можно, конечно. в самом тесте извлекать строку, обрезать до нужного размера, и только тогда сравнивать, но это может повлечь за собой другие ошибки. Может указать, какая должна быть длина строки в самом задании?

2016-09-25 09:29 UTC, kuzaleks commented on test_struct/src/test_str.h
> +        //cout << "__________" << endl;
Please remove all the commented lines of code.

2016-09-25 09:35 UTC, kuzaleks reviewed
Why do wee need both files test_struct/str.cpp and test_struct/str_full.cpp? If they just provide some utils for testing purposes, let's leave only one of them.

2016-09-25 09:36 UTC, kuzaleks requested changes
Let's rename str.cpp into utils.cpp.

2016-09-25 09:38 UTC, kuzaleks requested changes
Please, make sure that all the identifiers names conform to lowerCamelCase convention (e.g. outFile instead of out_file)

2016-09-25 09:40 UTC, kuzaleks commented on test_struct/src/str.h
> +	int cource;
let's call int year

2016-09-25 09:41 UTC, kuzaleks commented on test_struct/src/test_str.h
> +      TSM_ASSERT_EQUALS("The general case hasn't passed the test!", isEqualFiles("start_general_case.bin", "ready_general_case.bin"), true);
Could you please write in more details what does general case mean.

2016-10-02 09:15 UTC, kuzaleks commented
@lirik30 Зачем нам по-прежнему нужны аж три файлика, которые, во-многом, дублируют код друг-друга: str.cpp, str_full.cpp и utils.cpp. Почему бы не перенсти все вспомогательные функции в utils.cpp, а str.cpp, str_full.cpp просто бы не удалить?
Удалять файлы из git repo можно командой `git rm <file_name>`

2016-10-02 09:22 UTC, kuzaleks commented
@lirik30 кроме того, давайте договоримся все нужные файлы с исходным кодом помещаь в папку **src**. Для всех файлов, которые тестируют конкретную задачу создавайте подпапку в **src**. Например, если вы пишите тесты для задачи 6.4 -- отправляйте все файлы, которые реализуют эти тесты в папку **src/task_6_4/** (команда `git mv <from> <to>`).

2016-10-02 13:40 UTC, lirik30 commented
Ready

2016-10-16 10:04 UTC, kuzaleks approved these changes

2016-10-16 10:05 UTC, merged